import { cp, mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { resolve, join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const output = resolve(root, '.pages-dist');
// Remove only our marked, generated directory; never a repository or arbitrary path.
if (dirname(output) !== root)
  throw new Error('Invalid Pages build destination');
let exists = false;
try {
  await readFile(join(output, '.tesoob-generated'));
  exists = true;
} catch (error) {
  if (error.code !== 'ENOENT') throw error;
}
if (!exists) {
  try {
    await stat(output);
    throw new Error(
      'Refusing to overwrite an unmarked Pages output directory.',
    );
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }
}
if (exists) await rm(output, { recursive: true });
await mkdir(output, { recursive: true });
await cp(join(root, 'dist/client'), output, { recursive: true });
const worker = join(output, '_worker.js');
await mkdir(worker, { recursive: true });
await cp(join(root, 'dist/server'), join(worker, 'server'), {
  recursive: true,
  filter: (path) =>
    !path.endsWith('wrangler.json') &&
    !path.includes(`${process.platform === 'win32' ? '\\' : '/'}.vite`) &&
    !path.endsWith('.map'),
});
await cp(join(root, 'deploy/pages-entry.js'), join(worker, 'index.js'));
await writeFile(
  join(output, '_routes.json'),
  JSON.stringify({
    version: 1,
    include: ['/*'],
    exclude: ['/media/*', '/fonts/*', '/_next/static/*'],
  }),
);
await writeFile(
  join(output, '.tesoob-generated'),
  'Generated by scripts/build-pages.mjs; safe to rebuild.',
);
// Vite emits a Workers deploy redirect. Pages needs its own root configuration.
await mkdir(join(root, '.wrangler/deploy'), { recursive: true });
await writeFile(
  join(root, '.wrangler/deploy/config.json'),
  JSON.stringify({ configPath: '../../wrangler.jsonc' }),
);
console.log(
  'Pages artifact ready: .pages-dist (SSR + API in _worker.js, D1 binding DB).',
);
